### PR TITLE
Remove references to autoprefixer and postcss

### PR DESCRIPTION
**Pull request by evoactivity**
PostCSS is not needed to use tailwind as applied by this recipe.

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
thank you!!!

**Comment by NullVoxPopuli** [comment]
in the `ember-apply` directory, can you run `yarn test --update`? and then commit/push again?

snapshots need updated (diff looks correct for what we want)

**Comment by evoactivity** [comment]
`--update` doesn't seem to be an available flag

```
❯ yarn test --update
yarn run v1.22.17
$ turbo run test --update
 ERROR  unknown flag: --update
error Command failed with exit code 1.
```

**Comment by NullVoxPopuli** [comment]
potentially a Mac vs Linux thing. no worries -- I'll take a look

**Pull request merged**
