### PR TITLE
fix: don't add ="" to data-embroider-ignore boolean attribute (fix #353)

### LINKED ISSUE #353: posthtml rewrites `data-embroider-ignore` as `data-embroider-ignore=""`
This doesn't seem to actually break anything (output is still valid), but it is annoying to have meaningless/noise changes introduced. I think we could fix this by using https://github.com/posthtml/posthtml-boolean-attributes

```js
const recast = require('ember-template-recast');
const posthtml = require('posthtml');
const template = `<script src="/testem.js" integrity="" data-embroider-ignore></script>`;
console.log('recast', recast.print(recast.parse(template)));
posthtml([]).process(template).then((result) => {
  console.log('posthtml', result.html);
});
// Output:
// recast <script src="/testem.js" integrity="" data-embroider-ignore></script>
// posthtml <script src="/testem.js" integrity="" data-embroider-ignore=""></script>
```

https://github.com/NullVoxPopuli/ember-apply/blob/6074babad5e2ff4a86751c454bc91ce3d842a5f9/ember-apply/tests/__snapshots__/cli.test.ts.snap#L122

### PR DESCRIPTION
**Pull request by jacobq**

### CODE REVIEW

**Comment by jacobq** [comment]
Can you check / update the testing snapshots? I am willing but ignorant.

**Comment by NullVoxPopuli** [comment]
I think the command for updating only includes `--update` after running the tests.

So, `yarn test --update`

Lemme know of issues!

**Comment by jacobq** [comment]
> So, `yarn test --update`

Done

**Comment by NullVoxPopuli** [comment]
Looks like there in still an error. Probably os-related, as snapshots have historically been generated on linux.

I'll push an update when I get to a computer 🙃

**Comment by jacobq** [comment]
> Reviewing diffs of diffs is weird. lol.

Soon we'll need a [Merkle tree](https://en.wikipedia.org/wiki/Merkle_tree) 🤣

**Pull request merged**
